# 1. Specifica l'immagine base
FROM python:3.9-alpine 

# 2. Specifica la directory di lavoro
WORKDIR /app

# 3. Copia il file app.py nella directory di lavoro
COPY app.py . 

# 4. Specifica il comando da eseguire
CMD ["python", "app.py"]